--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25/02/2018 12:03:52
-- Server version: 5.5.5-10.1.26-MariaDB
-- Client version: 4.1
--


--
-- Definition for database escaladapp
--
DROP DATABASE IF EXISTS escaladapp;
CREATE DATABASE IF NOT EXISTS escaladapp
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE escaladapp;

--
-- Definition for table mountains
--
CREATE TABLE IF NOT EXISTS mountains (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  altitude FLOAT DEFAULT NULL,
  location VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  description TEXT CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 27
AVG_ROW_LENGTH = 2048
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table users
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) DEFAULT NULL,
  password VARCHAR(30) NOT NULL,
  name VARCHAR(50) DEFAULT NULL,
  surname VARCHAR(50) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  creationDate DATE NOT NULL,
  administrator TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE INDEX username (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 10
AVG_ROW_LENGTH = 8192
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table climbed
--
CREATE TABLE IF NOT EXISTS climbed (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user INT(11) DEFAULT NULL,
  mountain INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_climbed_mountains_id FOREIGN KEY (mountain)
    REFERENCES mountains(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_climbed_users_id FOREIGN KEY (user)
    REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table favourites
--
CREATE TABLE IF NOT EXISTS favourites (
  user INT(11) DEFAULT NULL,
  mountain INT(11) DEFAULT NULL,
  CONSTRAINT FK_favourites_mountains_id FOREIGN KEY (mountain)
    REFERENCES mountains(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_favourites_users_id FOREIGN KEY (user)
    REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table mountains
--
INSERT INTO mountains VALUES
(17, 'Teide', 3718, 'Tenerife', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Teide2007.jpg/1280px-Teide2007.jpg', '<p>El <strong>Teide</strong> es un volcán situado en la isla de Tenerife (Canarias, España). Tiene una altitud de 3.718 metros sobre el nivel del mar y 7.500 metros sobre el lecho oceánico, es el pico más alto del país, el de cualquier tierra emergida del océano Atlántico y el tercer mayor volcán de la Tierra desde su base en el lecho oceánico, después del Mauna Kea y el Mauna Loa, ambos en Hawái. La altitud del Teide convierte además a la isla de Tenerife en la décima isla más alta del mundo.<br /></p>'),
(18, 'Mulhacén', 3479, 'Granada', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Mulhacen_north_face.JPG', '<p>El <strong>Mulhacén</strong>, con una altitud de 3.478,6&nbsp;msnm, es el pico más alto de la península ibérica y el segundo de España tras el Teide, de 3.718&nbsp;msnm (Tenerife, Canarias). El Mulhacén forma parte del parque nacional de Sierra Nevada. Está enclavado en la provincia de Granada, en el sur peninsular de España, y pertenece a Sierra Nevada, en la cordillera Penibética.<br /></p>'),
(19, 'Aneto', 3404, 'Aragón', 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Cima_aneto-01.jpg', '<p>El <strong>Aneto</strong> es el pico más elevado de los Pirineos, con una altitud de 3404 metros sobre el nivel del mar. Se encuentra situado en el Parque Natural Posets-Maladeta, en el municipio de Benasque, provincia de Huesca, comunidad autónoma de Aragón, en España.<br /></p>'),
(20, 'Veleta', 3396, 'Andalucía', 'https://upload.wikimedia.org/wikipedia/commons/7/72/450px-CILINDRO.JPG', '<p>El <strong>Pico del Veleta</strong> es, con una altitud de 3395,68&nbsp;msnm, la cuarta cumbre más alta de España y segunda de su cordillera, sólo por detrás del Teide (Tenerife), Mulhacén (Sierra Nevada) y Aneto (Pirineos). Está enclavado en la provincia de Granada, en Andalucía (España), y pertenece a Sierra Nevada, en la cordillera Penibética. Su coordenada UTM es 30S 675013, tomando el elipsoide Hayford. Su superficie se reparte entre los Parques Natural y Nacional de Sierra Nevada. Administrativamente en su cumbre confluyen los términos muncipales de Dílar, Monachil, Güéjar Sierra y Capileira.<br /></p>'),
(21, 'Posets o Llardana', 3371, 'Aragón', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Pico_Posets_from_Forqueta.jpg', '<p>El <strong>pico Posets</strong> o <strong>Punta de Llardana</strong> es el segundo pico más alto de los Pirineos, tras el Aneto. Tiene una altitud de 3.375 metros y se encuentra en el norte de la provincia de Huesca (Aragón). Forma parte de la ruta: Pico Posets, Pico Perdiguero y Pico Aneto.<br /></p>'),
(22, 'La Alcazaba', 3366, 'Andalucía', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/JDCANO_ALCAZABA.JPG', '<p>La <strong>Alcazaba</strong> es, con 3.371 metros, la sexta cumbre más alta de España, por detrás del Teide (3.718 m), Mulhacén (3.482 m), Pico de Aneto (3.404 m), Pico del Veleta (3.396 m) y Pico Posets (3.375 m).<br /></p>'),
(23, 'Monte Perdido', 3355, 'Aragón', 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Macizo_perdido.jpg', '<p><strong>Monte Perdido</strong> (en aragonés <em>As Tres Serols</em>) es el macizo calcáreo más alto de Europa. Se encuentra situado dentro de la vertiente sur del Pirineo central, al norte de la provincia de Huesca, en el parque nacional de Ordesa y Monte Perdido, en la comunidad autónoma de Aragón, España. Su pico más elevado es el Monte Perdido con una altitud de 3.355 metros sobre el nivel del mar.<br /></p>'),
(24, 'Cilindro', 3328, 'Aragón', 'https://upload.wikimedia.org/wikipedia/commons/7/72/450px-CILINDRO.JPG', '<p>El <strong>pico Cilindro</strong>, también llamado <strong>Cilindro de Marboré</strong>, es un pico de 3.328 m de altitud del macizo de Monte Perdido, dentro de la cordillera del Pirineo y que se sitúa íntegramente en España (Valle de Ordesa), pero muy cerca de la frontera con Francia (Circo de Gavarnie) con la que limita el Pico Marboré, estando incluido en el español Parque Nacional de Ordesa y Monte Perdido y cercano al Parque Nacional de los Pirineos.<br /></p>'),
(25, 'Perdiguero', 3321, 'Aragón', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Pico_Perdiguero_1.jpg', '<p>El <strong>pico Perdiguero</strong> (<em>francés: Pic de Perdiguère</em>) es una cumbre de los Pirineos, situada entre Aragón y Alto Garona, como frontera divisoria entre España y Francia.</p>\r\n<p>Tiene tres vías principales de ascensión: La que parte desde el Barranco de Literola, la que se inicia en el Valle de Estós y la que asciende en el Valle de Remuñe.</p>\r\n<p>Desde su cumbre hay un amplia visión del Pirineo oscense y francés. Y del macizo de la Maladeta y Posets</p>\r\n<p><br /></p>'),
(26, 'Maladeta', 3308, 'Aragón', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Maladeta.jpg', '<p>El <strong>Pico de la Maladeta</strong> es una cumbre montañosa de 3.308 metros de altitud, próxima al Pico Aneto. Se encuentra situado en el Parque natural Posets-Maladeta, en el municipio de Benasque, provincia de Huesca, comunidad autónoma de Aragón, en España. En su ladera norte se encuentra el denominado Glaciar de la Maladeta, con unas 37&nbsp;ha de superficie total. Está fraccionado en dos partes, Maladeta occidental (6 ha) y oriental (31 ha).<br /></p>');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(7, 'admin', 'YWRtaW4=', NULL, NULL, 'admin@istra.dor', '2018-02-20', 1),
(8, 'user', 'dXNlcg==', NULL, NULL, 'us@ua.rio', '2018-02-20', 0),
(9, 'test', 'dGVzdA==', NULL, NULL, 'testeo@test.com', '2018-02-20', 0);

-- 
-- Dumping data for table climbed
--

-- Table escaladapp.climbed does not contain any data (it is empty)

-- 
-- Dumping data for table favourites
--
INSERT INTO favourites VALUES
(9, 17),
(9, 18);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;